### ISSUE TITLE
error when PodSecurityStandard `restricted` is enabled

### ISSUE THREAD

**Issue by gprossliner** [clbx/kubectl-browse-pvc#27]
When you use the tool to browse a PVC on an namespace which has the [restricted](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted) Pod Security Standard applied, job creation fails with an error like this:

```
W0313 10:00:40.734960   92216 warnings.go:70] would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "browser" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "browser" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "browser" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "browser" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
```

When checking the created `Job` object, the following changes would make the Job compatible to it, as tested manually:

```yaml
 containers:
 - name: browser
    securityContext:
      runAsUser: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      seccompProfile: 
        type: RuntimeDefault
```

Things to mention if you would consider this bug to be fixed / feature to be implemented:
* The `runAsUser` / `runAsGroup` fields would benefit by being controlled by the user with a arg, because it may be important to match existing file permissions.
* Detecting if a specific PSS is active on a given namespace is not as easy as it might look, bc adding a label to the namespace is not the only option to set a label. By using the [Admission Controller](https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller/) the user can also define an `--admission-control-config-file`, which is AFAIK not accessible over the API, and which **don't result in the namespaces being labled!**. `kubectl describe ns` don't show that applied PSS either.
* Maybe it would be best to allow the user to opt-in with `--runAsUser` / `--runAsGroup` args that would enable the the `restricted` specs.

What do you think?
Please ping me if you need assistance.
